import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'


import Slider from "./ui/slider";
import Footer1 from './ui/footer';
import Aliados from './ui/aliados';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Club LPG',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
      <Slider/>
    <hr/>
    <hr/>
    <h1></h1>
    <hr/>
    <hr/>
    <div>
    <Aliados/>
    </div>
      
      <Footer1/>

  
      </body>
      
    </html>
  )
}
